version: '3.9'

services:
  db:
    image: postgres
    env_file:
      - ./proj/.env
  web:
    build:
      context: .
    command: gunicorn proj.wsgi:application --bind 0.0.0.0:8000 --reload
    ports:
      - 8000:8000
    volumes:
      - .:/code
    depends_on:
      db:
        condition: service_started