# Generated by Django 4.2 on 2023-04-18 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('url', models.CharField(max_length=200)),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE'), ('CONNECT', 'CONNECT'), ('HEAD', 'HEAD'), ('OPTIONS', 'OPTIONS'), ('TRACE', 'TRACE')], max_length=7)),
                ('client_ip', models.CharField(max_length=200)),
                ('headers', models.JSONField()),
                ('status', models.PositiveSmallIntegerField()),
                ('body', models.JSONField(blank=True, null=True)),
                ('body_content_type', models.CharField(blank=True, max_length=200, null=True)),
                ('response', models.JSONField(blank=True, null=True)),
                ('response_content_type', models.CharField(blank=True, max_length=200, null=True)),
                ('execution_time', models.FloatField()),
                ('is_slow', models.BooleanField(default=False)),
                ('is_pinned', models.BooleanField(default=False)),
                ('authenticated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
