# Generated by Django 4.2 on 2023-04-05 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_request_logger', '0001_squashed_0002_requestlog_execution_time_requestlog_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestlog',
            name='execution_time',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='requestlog',
            name='method',
            field=models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE'), ('CONNECT', 'CONNECT'), ('HEAD', 'HEAD'), ('OPTIONS', 'OPTIONS'), ('TRACE', 'TRACE')], max_length=7),
        ),
    ]
