# Generated by Django 4.2 on 2023-04-12 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_request_logger', '0003_alter_requestlog_execution_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestlog',
            name='response_content_type',
            field=models.CharField(default='text/html; charset=utf-8', max_length=200),
            preserve_default=False,
        ),
    ]
