# Generated by Django 4.2 on 2023-04-14 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_request_logger', '0004_requestlog_response_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestlog',
            name='client_ip',
            field=models.CharField(default='0.0.0.0', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requestlog',
            name='headers',
            field=models.JSONField(default='{}'),
            preserve_default=False,
        ),
    ]
