# Generated by Django 4.2 on 2023-04-14 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_request_logger', '0005_requestlog_client_ip_requestlog_headers'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestlog',
            name='is_slow',
            field=models.BooleanField(default=False),
        ),
    ]
