# Generated by Django 4.2 on 2023-04-14 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_request_logger', '0006_requestlog_is_slow'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestlog',
            name='body_content_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='requestlog',
            name='response_content_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
