# Generated by Django 4.2 on 2023-04-16 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_request_logger', '0007_requestlog_body_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestlog',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
    ]
